Initial Config
mywork/eslint-config-mywork pull request #1
Opened 2020-10-28 18:02 UTC by lucasdiaas

## Purpose
This PR adds the initial files for our `eslint-config` repo. It has some rules from `eslint/recommended` and other third party configs disabled to prevent conflicts with `prettier`. The disabled rules are the following:
- `eslint`
    - [function-paren-newline](https://eslint.org/docs/rules/function-paren-newline)
    - [implicit-arrow-linebreak](https://eslint.org/docs/rules/implicit-arrow-linebreak)
    - [indent](https://eslint.org/docs/rules/indent)
    - [newline-per-chained-call](https://eslint.org/docs/rules/newline-per-chained-call)
    - [no-confusing-arrow](https://eslint.org/docs/rules/no-confusing-arrow)
    - [nonblock-statement-body-position](https://eslint.org/docs/rules/nonblock-statement-body-position)
    - [object-curly-newline](https://eslint.org/docs/rules/object-curly-newline)
    - [operator-linebreak](https://eslint.org/docs/rules/operator-linebreak)

- `eslint-plugin-react`
    - [jsx-curly-newline](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-newline.md)
    - [jsx-wrap-multilines](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md)

## Changes
### Added
- added `index.js` and `typescript.js` files with the eslint rules
- added dependencies and peerDependencies to `package.json`

2020-10-28 18:13 UTC, espallargas approved these changes

2020-10-28 18:13 UTC, espallargas commented on index.js
> +    'react/jsx-curly-newline': 0,
colocar `off` sempre que estiver `0`

2020-10-28 18:13 UTC, espallargas commented on index.js
>  };
acho que tem que instalar o `prettier` e `eslint` com nossas regras aqui.

2020-10-28 18:13 UTC, espallargas commented on .github/pull_request_template.md
> +[MW-XX](https://myworkbrasil.atlassian.net/browse/MW-XX)
Eu instalei um plugin que reconhece o `MW-XX` e coloca o link. Então podemos tirar a url do template.

2020-10-28 18:13 UTC, espallargas commented on package.json
> +  "author": "Lucas Dias <lucasdiaas@outlook.com>",
mywork né irmão?!

2020-10-28 18:13 UTC, espallargas commented on package.json
> +  "peerDependencies": {
@leoagomes vc pode conferir se a dependencias estao corretas?

2020-10-28 18:13 UTC, espallargas commented on index.js
> +    'comma-dangle': 0,
ordernar

2020-10-28 18:13 UTC, espallargas commented on typescript.js
> +    'eslint:recommended',
ordernar

2020-10-28 18:16 UTC, espallargas requested changes

2020-10-28 18:16 UTC, espallargas commented on package.json
> +  "version": "1.0.0",
`0.0.1`

2020-10-28 18:29 UTC, espallargas reviewed
Ajustar LICENSE pra ser da mywork

2020-10-28 18:29 UTC, espallargas commented on .github/pull_request_template.md
> +## Purpose
colocar também um `README`

2020-10-30 15:17 UTC, espallargas approved these changes, later dismissed
@leoagomes eu li e juro que não entendi como funcionam direito peer dependencies. Então eu estou perdido quanto ao `package.json` e as instruções do `README`. Conto com sua magia para me ajudar a desvendar esse mistério.

2020-11-19 15:10 UTC, espallargas submitted a review, later dismissed

2020-11-19 18:00 UTC, espallargas approved these changes

2020-11-19 18:01 UTC, leoagomes approved these changes

2020-11-19 18:01 UTC, merged